name: Deploy Forgejo Runner

on:
  workflow_dispatch:

jobs:
  deploy-runner:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Launch EC2 instance for Forgejo runner
        run: |
          aws ec2 run-instances \
            --image-id ami-0c2b8ca1dad447f8a \
            --count 1 \
            --instance-type t2.micro \
            --key-name forgejo-runner-key \
            --security-groups forgejo-runner-sg \
            --iam-instance-profile Name=ForgejoRunnerRole \
            --user-data file://bootstrap.sh \
            --tag-specifications 'ResourceType=instance,Tags=[{Key=Name,Value=forgejo-runner}]'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
